version: "3.9"

x-common-variables: &common-variables
  TG_MONGODB_HOST: ${TG_MONGODB_HOST}
  TG_MONGODB_PASSWORD: ${TG_MONGODB_PASSWORD}
  TG_MONGODB_USERNAME: ${TG_MONGODB_USERNAME}

services:
  front:
    image: front
    build:
      dockerfile: Dockerfile
      context: ./front
    container_name: front
    hostname: front
    ports:
      - 80:80
    environment:
      - REACT_APP_API_HOST=${REACT_APP_API_HOST}
  usuarios:
    image: usuarios
    build:
      dockerfile: Dockerfile
      context: ./users-api
    container_name: usuarios
    hostname: usuarios
    ports:
      - 8082:8082
    environment:
      - MONGO_DETAILS=mongodb://{TG_MONGODB_HOST}:27017
      - MONGO_DB=db_users
      - MONGO_COLLECTION=users
      - PYTHONPATH=/code
      - SECRET_KEY=nA4QjrndALVotmHd0gG2fUHxLcJ6BA9IW0gPUkREMsykPUP-IA-Q6s_a_CUanCE0BpfVpGIlzGNg9QhYly2m7ZtSaNmhRyrdZBHYuoTR1qTFg5CNNjp0-5Tym75K5YNH3nWGXIgy-dfy3wsh3Dwm-8Aaj4xtIqNqacyRMcrPTck
  productos_bogota:
    image: productos
    build:
      dockerfile: Dockerfile
      context: ./productos-api
    container_name: productos-bog
    hostname: productos-bog
    ports:
      - 8085:8085
    environment:
      <<: *common-variables
      TG_CITY: BOG
      TG_PORT: 8085
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${TG_MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${TG_MONGODB_PASSWORD}
  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${TG_MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${TG_MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  data: {}
